<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BusinessSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            ['key' => 'restaurant_open_time', 'value' => '07:11', 'created_at' => '2021-01-06 05:55:51', 'updated_at' => '2021-01-06 05:55:51'],
            ['key' => 'restaurant_close_time', 'value' => '01:20', 'created_at' => null, 'updated_at' => null],
            ['key' => 'restaurant_name', 'value' => 'eFood', 'created_at' => null, 'updated_at' => null],
            ['key' => 'currency', 'value' => 'USD', 'created_at' => null, 'updated_at' => null],
            ['key' => 'logo', 'value' => '2021-05-29-60b1f342a8631.png', 'created_at' => null, 'updated_at' => null],
            ['key' => 'mail_config', 'value' => '{"status":0,"name":"Delivery APP","host":"mail.demo.com","driver":"smtp","port":"587","username":"info@demo.com","email_id":"info@demo.com","encryption":"tls","password":"demo"}', 'created_at' => null, 'updated_at' => '2024-11-18 10:06:04'],
            ['key' => 'delivery_charge', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'ssl_commerz_payment', 'value' => '{"status":"0","store_id":null,"store_password":null}', 'created_at' => null, 'updated_at' => '2021-07-25 14:38:25'],
            ['key' => 'paypal', 'value' => '{"status":"0","paypal_client_id":null,"paypal_secret":null}', 'created_at' => null, 'updated_at' => '2021-07-25 14:38:48'],
            ['key' => 'stripe', 'value' => '{"status":"0","api_key":null,"published_key":null}', 'created_at' => null, 'updated_at' => '2021-07-25 14:38:57'],
            ['key' => 'phone', 'value' => '+01747413273', 'created_at' => null, 'updated_at' => null],
            ['key' => 'footer_text', 'value' => 'copyright', 'created_at' => null, 'updated_at' => null],
            ['key' => 'address', 'value' => 'lorem ipsum dollar', 'created_at' => null, 'updated_at' => null],
            ['key' => 'email_address', 'value' => 'lorem@ipsum.com', 'created_at' => null, 'updated_at' => null],
            ['key' => 'cash_on_delivery', 'value' => '{"status":"1"}', 'created_at' => null, 'updated_at' => '2021-02-11 18:39:36'],
            ['key' => 'email_verification', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'digital_payment', 'value' => '{"status":"1"}', 'created_at' => '2021-01-30 19:38:54', 'updated_at' => '2021-01-30 19:38:58'],
            ['key' => 'terms_and_conditions', 'value' => '<div class="ql-editor" data-gramm="false" contenteditable="true"><h1>Terms and Condition</h1><p><br></p><ol><li>Hello, terms and conditions.......</li><li>Hello</li></ol></div><div class="ql-clipboard" contenteditable="true" tabindex="-1"></div><div class="ql-tooltip ql-hidden"><a class="ql-preview" target="_blank" href="about:blank"></a><input type="text" data-formula="e=mc^2" data-link="https://quilljs.com" data-video="Embed URL"><a class="ql-action"></a><a class="ql-remove"></a></div>', 'created_at' => null, 'updated_at' => '2021-02-11 18:31:50'],
            ['key' => 'fcm_topic', 'value' => '', 'created_at' => null, 'updated_at' => null],
            ['key' => 'fcm_project_id', 'value' => '3f34f34', 'created_at' => null, 'updated_at' => null],
            ['key' => 'push_notification_key', 'value' => 'demo', 'created_at' => null, 'updated_at' => null],
            ['key' => 'order_pending_message', 'value' => '{"status":1,"message":"Your order has been placed successfully."}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'order_processing_message', 'value' => '{"status":1,"message":"Your order is going to the cook"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'out_for_delivery_message', 'value' => '{"status":0,"message":"Order out for delivery."}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'order_delivered_message', 'value' => '{"status":1,"message":"delivered"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'delivery_boy_assign_message', 'value' => '{"status":1,"message":"boy assigned"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'delivery_boy_start_message', 'value' => '{"status":1,"message":"start delivery"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'delivery_boy_delivered_message', 'value' => '{"status":1,"message":"boy delivered"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'order_confirmation_msg', 'value' => '{"status":1,"message":"Your order has been confirmed."}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'razor_pay', 'value' => '{"status":"0","razor_key":null,"razor_secret":null}', 'created_at' => '2021-02-14 10:15:12', 'updated_at' => '2021-07-25 14:38:34'],
            ['key' => 'location_coverage', 'value' => '{"status":1,"longitude":"91.410747","latitude":"22.986282","coverage":"20"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'minimum_order_value', 'value' => '50', 'created_at' => null, 'updated_at' => null],
            ['key' => 'point_per_currency', 'value' => '50', 'created_at' => null, 'updated_at' => null],
            ['key' => 'internal_point', 'value' => '{"status":null}', 'created_at' => '2021-04-24 01:50:19', 'updated_at' => '2021-04-24 01:50:19'],
            ['key' => 'senang_pay', 'value' => '{"status":"0","secret_key":null,"merchant_id":null}', 'created_at' => '2021-04-24 01:58:21', 'updated_at' => '2021-07-25 14:39:23'],
            ['key' => 'privacy_policy', 'value' => '<div class="ql-editor" data-gramm="false" contenteditable="true" spellcheck="false"><p>privacy policy</p></div><grammarly-extension data-grammarly-shadow-root="true" style="position: absolute; top: 0px; left: -1px; pointer-events: none; z-index: auto;" class="cGcvT"></grammarly-extension><div class="ql-clipboard" contenteditable="true" tabindex="-1"></div><div class="ql-tooltip ql-hidden"><a class="ql-preview" target="_blank" href="about:blank"></a><input type="text" data-formula="e=mc^2" data-link="https://quilljs.com" data-video="Embed URL"><a class="ql-action"></a><a class="ql-remove"></a></div>', 'created_at' => null, 'updated_at' => '2021-04-28 03:36:02'],
            ['key' => 'about_us', 'value' => '<div class="ql-editor" data-gramm="false" contenteditable="true" spellcheck="false"><p><strong><em>hello world </em></strong></p><p><strong><em>nice </em></strong></p></div><grammarly-extension data-grammarly-shadow-root="true" style="position: absolute; top: 0px; left: -1px; pointer-events: none; z-index: auto;" class="cGcvT"></grammarly-extension><grammarly-extension data-grammarly-shadow-root="true" style="mix-blend-mode: darken; position: absolute; top: 0px; left: -1px; pointer-events: none; z-index: auto;" class="cGcvT"></grammarly-extension><div class="ql-clipboard" contenteditable="true" tabindex="-1"></div><div class="ql-tooltip ql-hidden"><a class="ql-preview" target="_blank" href="about:blank"></a><input type="text" data-formula="e=mc^2" data-link="https://quilljs.com" data-video="Embed URL"><a class="ql-action"></a><a class="ql-remove"></a></div>', 'created_at' => null, 'updated_at' => '2021-05-23 18:29:52'],
            ['key' => 'paystack', 'value' => '{"status":"0","publicKey":null,"secretKey":null,"paymentUrl":"https:\/\/api.paystack.co","merchantEmail":null}', 'created_at' => '2021-05-04 14:38:35', 'updated_at' => '2021-07-25 14:39:12'],
            ['key' => 'time_zone', 'value' => 'Asia/Almaty', 'created_at' => null, 'updated_at' => null],
            ['key' => 'maintenance_mode', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'currency_symbol_position', 'value' => 'right', 'created_at' => null, 'updated_at' => null],
            ['key' => 'language', 'value' => '[{"id":1,"name":"en","direction":"ltr","code":"en","status":1,"default":true}]', 'created_at' => null, 'updated_at' => '2022-06-07 10:59:59'],
            ['key' => 'self_pickup', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'delivery', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'phone_verification', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'msg91_sms', 'value' => '{"status":0,"template_id":null,"authkey":null}', 'created_at' => null, 'updated_at' => null],
            ['key' => '2factor_sms', 'value' => '{"status":"0","api_key":null}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'nexmo_sms', 'value' => '{"status":0,"api_key":null,"api_secret":null,"signature_secret":"","private_key":"","application_id":"","from":null,"otp_template":null}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'twilio_sms', 'value' => '{"status":0,"sid":null,"token":null,"from":null,"otp_template":null}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'pagination_limit', 'value' => '10', 'created_at' => null, 'updated_at' => null],
            ['key' => 'map_api_key', 'value' => '', 'created_at' => null, 'updated_at' => null],
            ['key' => 'delivery_management', 'value' => '{"status":0,"min_shipping_charge":0,"shipping_per_km":0}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'bkash', 'value' => '{"status":"1","api_key":"","api_secret":"","username":"","password":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'paymob', 'value' => '{"status":"1","api_key":"","iframe_id":"","integration_id":"","hmac":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'flutterwave', 'value' => '{"status":"1","public_key":"","secret_key":"","hash":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'mercadopago', 'value' => '{"status":"1","public_key":"","access_token":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'returned_message', 'value' => '{"status":0,"message":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'failed_message', 'value' => '{"status":0,"message":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'canceled_message', 'value' => '{"status":0,"message":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'recaptcha', 'value' => '{"status":"0","site_key":"","secret_key":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'firestore_db', 'value' => '{"apiKey":"","authDomain":"","projectId":"","storageBucket":"","messagingSenderId":"","appId":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'play_store_config', 'value' => '{"status":"","link":"","min_version":"1"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'app_store_config', 'value' => '{"status":"","link":"","min_version":"1"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'default_preparation_time', 'value' => '30', 'created_at' => null, 'updated_at' => null],
            ['key' => 'decimal_point_settings', 'value' => '2', 'created_at' => null, 'updated_at' => null],
            ['key' => 'schedule_order_slot_duration', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'time_format', 'value' => '24', 'created_at' => null, 'updated_at' => null],
            ['key' => 'wallet_status', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'loyalty_point_status', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'ref_earning_status', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'loyalty_point_exchange_rate', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'ref_earning_exchange_rate', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'loyalty_point_item_purchase_point', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'loyalty_point_minimum_point', 'value' => '0', 'created_at' => null, 'updated_at' => null],
            ['key' => 'whatsapp', 'value' => '{"status":0,"number":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'fav_icon', 'value' => '', 'created_at' => null, 'updated_at' => null],
            ['key' => 'cookies', 'value' => '{"status":"1","text":"Allow Cookies for this site"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'maximum_otp_hit', 'value' => '5', 'created_at' => null, 'updated_at' => null],
            ['key' => 'otp_resend_time', 'value' => '60', 'created_at' => null, 'updated_at' => null],
            ['key' => 'temporary_block_time', 'value' => '600', 'created_at' => null, 'updated_at' => null],
            ['key' => 'dm_self_registration', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'toggle_veg_non_veg', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'maximum_login_hit', 'value' => '5', 'created_at' => null, 'updated_at' => null],
            ['key' => 'temporary_login_block_time', 'value' => '600', 'created_at' => null, 'updated_at' => null],
            ['key' => 'return_page', 'value' => '{"status":"0","content":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'refund_page', 'value' => '{"status":"0","content":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'cancellation_page', 'value' => '{"status":"0","content":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'offline_payment', 'value' => '{"status":"1"}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'guest_checkout', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'partial_payment', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'partial_payment_combine_with', 'value' => 'all', 'created_at' => null, 'updated_at' => null],
            ['key' => 'qr_code', 'value' => '{"branch_id":"1","logo":"","title":"","description":"","opening_time":"","closing_time":"","phone":"","website":"","social_media":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'apple_login', 'value' => '{"login_medium":"apple","client_id":"","client_secret":"","team_id":"","key_id":"","service_file":"","redirect_url":"","status":0}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'add_wallet_message', 'value' => '{"status":0,"message":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'add_wallet_bonus_message', 'value' => '{"status":0,"message":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'firebase_otp_verification', 'value' => '{"status":0,"web_api_key":""}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'footer_description_text', 'value' => '', 'created_at' => null, 'updated_at' => null],
            ['key' => 'push_notification_service_file_content', 'value' => '', 'created_at' => null, 'updated_at' => null],
            ['key' => 'maintenance_system_setup', 'value' => '[]', 'created_at' => null, 'updated_at' => null],
            ['key' => 'maintenance_duration_setup', 'value' => '{"maintenance_duration":"until_change","start_date":null,"end_date":null}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'maintenance_message_setup', 'value' => '{"business_number":1,"business_email":1,"maintenance_message":"We are Cooking Up Something Special!","message_body":"Our system is currently undergoing maintenance to bring you an even tastier experience. Hang tight while we make the dishes."}', 'created_at' => null, 'updated_at' => null],
            ['key' => 'google_map_status', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'admin_order_notification', 'value' => '1', 'created_at' => null, 'updated_at' => null],
            ['key' => 'admin_order_notification_type', 'value' => 'manual', 'created_at' => null, 'updated_at' => null],
        ];

        DB::table('business_settings')->insert($settings);
    }
}